# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('street', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('thumbnail', models.TextField(blank=True, db_index=True, default=None, null=True)),
            ],
        ),
    ]
